import type {NextPage} from 'next'
import Head from 'next/head'

import PageLayout from 'components/layouts/page-layout'

const Home: NextPage = () => {
  return (
    <PageLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container flex flex-col items-center max-w-3xl leading-relaxed">
        <h2>Hi!</h2>
        <p className="mt-12">
          This is an another one{' '}
          <span className="font-bold">
            nextjs-typescript-mdx-tailwind-starter
          </span>{' '}
          that is TypeScript based and includes next features:
        </p>
        <ul className="max-w-sm mt-12 space-y-3 list-disc">
          <li>
            <a className="text-blue-500" href="https://tailwindcss.com/docs">
              tailwindcss
            </a>{' '}
            (with{' '}
            <a
              className="text-blue-500"
              href="https://github.com/tailwindlabs/tailwindcss-typography"
            >
              @tailwindcss/typography
            </a>
            )
          </li>
          <li>
            <span className="font-bold">MDX</span> support (with{' '}
            <a
              className="text-blue-500"
              href="https://github.com/vercel/next.js/tree/canary/packages/next-mdx"
            >
              @next/mdx
            </a>{' '}
            and{' '}
            <a
              className="text-blue-500"
              href="https://github.com/hashicorp/next-mdx-remote"
            >
              next-mdx-remote
            </a>{' '}
            and <span className="font-bold">frontmatter</span> support with{' '}
            <a
              className="text-blue-500"
              href="https://github.com/jonschlinkert/gray-matter"
            >
              gray-matter
            </a>
            )
          </li>
          <li>
            blog implemented (with{' '}
            <span className="font-bold">posts pagination</span>)
          </li>
          <li>
            <span className="font-bold">light/dark mode</span> implemented
          </li>
        </ul>
        <p className="mt-20">
          You can check it out on{' '}
          <a
            className="text-blue-500"
            href="https://github.com/DrShpongle/nextjs-typescript-mdx-tailwind-starter"
          >
            GitHub
          </a>
        </p>
      </div>
    </PageLayout>
  )
}

export default Home
